build-job:
  stage: build
  script:
    - echo "Checking Syntax for php Files"
    - cd /home/data/a7zj6USY/0/root/deployment
    - git show --name-only HEAD > /home/gitlab-runner/syntax_checker.txt
    - sed -i '1,6d' /home/gitlab-runner/syntax_checker.txt
    - for i in `cat /home/gitlab-runner/syntax_checker.txt` ; do php -l $i; done 2>&1 | tee /home/gitlab-runner/syntax_checker/output.txt
  tags:
    - dish2

test-job1:
  stage: test
  script:
    - echo "Checking code standard as per "
    - cp `cat /home/gitlab-runner/syntax_checker.txt` /home/gitlab-runner/code-review/
    - /home/gitlab-runner/magento-coding-standard/vendor/bin/phpcs --standard=Magento2 /home/gitlab-runner/code-review/ > /home/gitlab-runner/error_files.txt
    - sed 's/ \+/,/g' /home/gitlab-runner/error_files.txt > /home/gitlab-runner/error.csv
    - COUNT=`cat /home/gitlab-runner/error_files.txt  | grep "ERRORS" | awk '{print $2}' | awk '{Total=Total+$1} END{print Total}'`
  tags:
    - dish2

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  tags:
    - dish2
