stages:
#  - syntaxchecker
#  - codeaudit
# - unittest
  - Deploycode

Deploycode:
  stage: Deploycode
  script:
    - git fetch origin
    - git checkout -B feature origin/feature
    - git remote add Dev http://root:12345678@svrgitlab.com/root/localtest
    - git pull Dev feature
    - git push Dev feature:feature
  tags:
    - dish2
