build-job:
  stage: Code Review using Magento Code Standards
  script:
    - find /home/data/a7zj6USY/0/root/deployment/ -type f -mmin -280 -mmin +120 -exec cp "{}" /home/gitlab-runner/code-review/ \;
    - /home/gitlab-runner/magento-coding-standard/vendor/bin/phpcs --standard=Magento2 /home/gitlab-runner/code-review/ > /home/gitlab-runner/error_files.txt
    - sed 's/ \+/,/g' /home/gitlab-runner/error_files.txt > /home/gitlab-runner/error.csv
    - COUNT=`cat /home/gitlab-runner/error_files.txt  | grep "ERRORS" | awk '{print $2}' | awk '{Total=Total+$1} END{print Total}'`
    - if [ $COUNT > 0 ]; then mail -s "Magento Coding standards" sushil.rangari@gmail.com -A /home/gitlab-runner/error.csv < /home/gitlab-runner/magento-coding-standard/data.txt; else echo PASS; fi
  tags:
    - dish2

test-job1:
  stage: test
  script:
    - echo "installed git, made entry of svrgitlab on gitlab server to resolve locally"
  tags:
    - dish2
test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
  tags:
    - dish2
deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  tags:
    - dish2
