#stages:
#  - syntaxchecker
#  - codeaudit
#  - unittest

syntax_checker:
  stage: syntaxchecker
  script:
    - echo "Checking Syntax for php Files"
  only:
    - merge_requests
    - cd /home/data/a7zj6USY/0/root/deployment
    - git show --name-only HEAD > /home/gitlab-runner/syntax_checker.txt
    - sed -i '1,6d' /home/gitlab-runner/syntax_checker.txt
    - for i in `cat /home/gitlab-runner/syntax_checker.txt` ; do php -l $i; done 2>&1 | tee /home/gitlab-runner/syntax_checker/output.txt
  tags:
    - dish2
code_audit:
  stage: codeaudit
  script:
    - echo "Checking code standard as per "Coding Standards""
    - cp --parents `cat /home/gitlab-runner/syntax_checker.txt` /home/gitlab-runner/code-review/
    - /home/gitlab-runner/magento-coding-standard/vendor/bin/phpcs --standard=Magento2 /home/gitlab-runner/code-review/ > /home/gitlab-runner/error_files.txt
    - sed 's/ \+/,/g' /home/gitlab-runner/error_files.txt > /home/gitlab-runner/error.csv
    - VALUE=0
    - SIZE=`du -s /home/gitlab-runner/error_files.txt | awk '{print $1}'`; if [ $SIZE -eq $VALUE ]; then echo "Code Audit PASSED"; else COUNT=`cat /home/gitlab-runner/error_files.txt  | grep "ERRORS" | awk '{print $2}' | awk '{Total=Total+$1} END{print Total}'`; fi;
  tags:
    - dish2

Unit_test:
  stage: unittest
  script:
    - /bin/cp /home/gitlab-runner/unit-testing/phpunit.xml /home/data/a7zj6USY/0/root/deployment/dev/tests/unit/phpunit.xml
    - /home/data/a7zj6USY/0/root/deployment/vendor/bin/phpunit -c /home/data/a7zj6USY/0/root/deployment/dev/tests/unit/phpunit.xml > /home/gitlab-runner/unit-testing/testdata.txt 2>&1
    - exitcode=$?
    - if [ exitcode -ge 1 ]; then sed '/^\./d' /home/gitlab-runner/unit-testing/testdata.txt > /home/gitlab-runner/unit-testing/sed_command_to_remove_uwnated_characters.txt; else "Unit Test Passed";fi
    - sed '2,4d' /home/gitlab-runner/unit-testing/sed_command_to_remove_uwnated_characters.txt > /home/gitlab-runner/unit-testing/sed_command_to_remove_top2_4lines.txt
    - echo "Unit Test Details Sent to Dev Team"
  tags:
    - dish2
