stages:
#  - syntaxchecker
#  - codeaudit
# - unittest
  - Deploycode

Deploycode:
  stage: Deploycode
  script:
    - git fetch origin
    - git checkout -B main origin/main
    #- git remote add Dev http://root:12345678@svrgitlab.com/root/localtest
    - git pull Dev main
    - git push Dev main:main
  tags:
    - dish2
