build-job:
  stage: build
  script:
    - echo "Hieee"
  tags:
    - Devops-Runner

test-job1:
  stage: test
  script:
    - echo "installed git, made entry of svrgitlab on gitlab server to resolve locally"
  tags:
    - Devops-Runner

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
  tags:
    - Devops-Runner

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the branch."
  tags:
    - Devops-Runner
