stages:
 - Deploy

Deploy:
  stage: Deploy
  script:
    - git remote set-url origin git@github.com:SushilRangari/everythingok.git
    - git pull origin
    #- git pull mcloud release2
    - git checkout -B release2
    - git remote set-url mcloud git@github.com:SushilRangari/everythingok.git
    - git push mcloud release2:release2
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.DEV\d+/'
  tags:
    - dish2
