build-job:
  stage: build
  script:
    - echo "Hieee, $GITLAB_USER_LOGIN!"
  only:
    - tags
  except:
    - main
    - feature
    - origin/feature  
  tags:
    - dish2
  
test-job1:
  stage: test
  script:
    - echo "installed git, made entry of svrgitlab on gitlab server to resolve locally"
  tags:
    - dish2
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~/((DEVRELEASE))/
Test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
  only:
    - /.*(?<!-DEV01)$/I
  tags:
    - dish2
  #only:
    #- /*\./*\./*\./DEVRELEASE\./*\

    
deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_TAG branch."
  tags:
    - dish2
  only:
    - /v1\/release\